{% set name = "django-tex" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-tex-{{ version }}.tar.gz
  sha256: 0b763a3782fee20c85e2b564561f130af269f25b0499fdafd49e55befd6803f8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2
    - jinja2 >=2.9

test:
  imports:
    - django_tex
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/weinbusch/django-tex
  summary: A simple Django app to render Latex templates and compile them into PDF files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
